### ISSUE TITLE
Icons not loaded even with existing "legacy_known_devices.yaml" file

### ISSUE THREAD

**Issue by carvalr** [dmamontov/hass-miwifi#19]
I need help with icon setting for device trackers.

I have created the file "legacy_known_devices.yaml" as the documentations says to, but the icons are not loaded when the device tracker objects are created.
![image](https://user-images.githubusercontent.com/74059823/156805913-21bdf70f-3a49-4faa-8179-bb7d38cc42b2.png)

The items within the file are created as following:
```
DEVICE_123:
  **icon: mdi:cellphone**
  mac: 00:00:00:AA:00:AA
  name: Device_123
  picture:
  track: true
```
When checking the device_tracker entity, there is no icon.
![image](https://user-images.githubusercontent.com/74059823/156806416-d459eef7-4487-4a1b-9a32-f9f62c6f704f.png)

Is there any additional setup required to show the icon properly?
