### ISSUE TITLE
How i can add icons in Performance table?

### ISSUE THREAD

**Issue by SPEC1AL1ST** [dmamontov/hass-miwifi#21]
Hello
How i can add icons in Performance table?
Sorry for noob question but i not find guide in FAQ or README

**Comment by dmamontov** [comment]
It's added here: https://gist.github.com/dmamontov/e6fa1842c486388387aaf061d3a82818#file-perfomance_table-yml-L18

The example is correct for the latest version of flex-table-card

We set icons in objects directly through the hass interface

**Comment by SPEC1AL1ST** [comment]
Thank you!

**Comment by SPEC1AL1ST** [comment]
My friend, sorry, you can give me example with icons?
Im not understand how i can add icon to each equipment

**Comment by SPEC1AL1ST** [comment]
Anybody can help?

**Comment by dmamontov** [comment]
```yaml
- data: icon
   name: ' '
   modify: '"<ha-icon id=\"icon\" icon=\"" + x + "\"></ha-icon>"'
```

try like this
