### ISSUE TITLE
How can i make a auto task?

### ISSUE THREAD

**Issue by foreverlong** [dmamontov/hass-miwifi#76]
First of all, I'd like to say thank you to you for this repository. 
When I add my router in the HA, I want to select a task : when the device"A" is offline, my light will be turned off. But I don't know how to select it. I don't know what should i select in the trigger. Could you please help me? Thank you very much. And sorry for my bad English. Wish you have a good day. : )

**Comment by dmamontov** [comment]
@foreverlong something like this

```yaml
trigger:
    platform: state
    entity_id: device_tracker.miwifi_00_00_00_00_00_00
    to: "not_home"
  action:
    - service: light.turn_off
       target:
          entity_id: light.light_in_the_hall
```
